name: CI

on:
  pull_request:
  push: # required for actions/cache to work
    branches:
      - master

jobs:
  compile:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        libfuse: [libfuse-dev, libfuse3-dev]
        features: [ '', 'abi-7-19' ]

    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y ${{ matrix.libfuse }} build-essential

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: x86_64-unknown-linux-musl

      - name: Run tests
        run: |
          cargo build --all --all-targets --features=${{ matrix.features }}
          cargo build --all --all-targets --no-default-features
          cargo build --target=x86_64-unknown-linux-musl --no-default-features
          cargo test --all --features=${{ matrix.features }}
          cargo doc --all --no-deps --features=${{ matrix.features }}
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y libfuse-dev libfuse3-dev build-essential

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny@0.14

      - name: Run tests
        run: INTERACTIVE="" make pre

  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        test_group: [mount_tests, pjdfs_tests, xfstests]

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: INTERACTIVE="" make ${{ matrix.test_group }}

  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      # Note that this is a partial install of macFUSE, for a complete installation that would require to install the kernel extension
      # But that currently not possible without restarting the machine
      - name: Install macFUSE
        run: brew install --cask macfuse

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run tests
        # The macFuse kernel extension is not installed so we need to skip the unmount_no_send test
        run: cargo test --features=libfuse -- --skip unmount_no_send
        env:
          RUST_LOG: DEBUG
        timeout-minutes: 5

